name: "WSI POC with Chatbot"

on:
  push:
    branches: [master-mfe-chatbot]
    paths: ["wsi-poc-app/**", "wsi-poc-components/**", ".github/workflows/**"]
  pull_request:
    branches: [master-mfe-chatbot]
    paths: ["wsi-poc-app/**", "wsi-poc-components/**", ".github/workflows/**"]

jobs:
  build_components:
    name: WSI POC Components Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install node_modules
        working-directory: wsi-poc-components
        run: sudo npm install

      - name: Build Vue App
        working-directory: wsi-poc-components
        run: sudo npm run build

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy Vue App to Surge
        run: surge ./wsi-poc-components/dist wsi-poc-components-amlakhani.surge.sh --token ${{ secrets.SURGE_CHATBOT_TOKEN }}
  
  build_app:
    name: WSI POC APP Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install node_modules
        working-directory: wsi-poc-app
        run: sudo npm install
      
      - name: Environment Variables
        working-directory: wsi-poc-app
        run: |
          touch .env
          echo "VUE_APP_CHATBOT_ID=${{ secrets.VUE_APP_CHATBOT_ID }}" > .env
          cat .env

      - name: Build Vue App
        working-directory: wsi-poc-app
        run: sudo npm run build

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy Vue App to Surge
        run: surge ./wsi-poc-app/dist wsi-poc-chatbot-app-amlakhani.surge.sh --token ${{ secrets.SURGE_CHATBOT_TOKEN_2 }}
